# Partimos de una base oficial de python
FROM python:2.7-slim
# El directorio de trabajo es desde donde se ejecuta el contenedor al iniciarse
WORKDIR /app
# Copiamos todos los archivos del build context al directorio /app del contenedor
COPY app.py /app
# Ejecutamos pip para instalar las dependencias en el contenedor
RUN pip install --upgrade pip
#RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN pip install Flask
RUN pip install Redis
# Indicamos que este contenedor se comunica por el puerto 80/tcp
EXPOSE 80
# Declaramos una variable de entorno
ENV NAME World
# Ejecuta nuestra aplicación cuando se inicia el contenedor
CMD ["python", "app.py"]
