version: '2'

services:
   nginx:
     image: nginxdemos/hello:latest
     restart: always
     labels:
       - "traefik.enable=true"
     labels:
      - "traefik.backend=weblocal"
      - "traefik.frontend.rule=Host:weblocal.curso.local"
      - "traefik.docker.network=traefik"
     restart: always
     networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
